apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  annotations:
    harness.io/skip-versioning: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | quote }}
